[project]
name = "npf-retail"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "databricks-connect==16.1.0",
    "databricks-sdk>=0.65.0",
    "ipykernel>=6.30.1",
    "pandas>=2.0.0",
]
